### ISSUE TITLE
Fidelity sell order doesn't work

### ISSUE THREAD

**Issue by cameronchu1** [Prem-ium/Auto-StockTrader#16]
When the Fidelity sell order execute up to this command, it fails:
click         css=#market-yes s-slot

It can't select Market order from the button dropdown list in the step, so it can't reach the "preview Order" stage.

**Comment by Prem-ium** [comment]
Hello,

I just tested out the Fidelity sell test with no issues, however others have reported having issues with the same line. The issue is likely due to your specific UI view on Fidelity, it is possible you have beta features or visuals enabled preventing the button from being pressed. You can tinker around with the beta view toggles to see if that solves the issue.

**Comment by cameronchu1** [comment]
Hi Prem,
Thanks for your support. I can't find the fidelity web page with the beta view toggle on it. Can you point me the web link so I can try it out. What web browser are you using?

Thanks,Kan
    On Tuesday, May 23, 2023 at 05:44:54 AM PDT, Prem Patel ***@***.***> wrote:  
 
 


Hello,

I just tested out the Fidelity sell test with no issues, however others have reported having issues with the same line. The issue is likely due to your specific UI view on Fidelity, it is possible you have beta features or visuals enabled preventing the button from being pressed. You can tinker around with the beta view toggles to see if that solves the issue.

**Comment by Prem-ium** [comment]
You can find the toggle for the view on the portfolio page on web view. I'm using Chrome and Edge browser. > Thanks,Kan On Tuesday, May 23, 2023 at 05:44:54

**Comment by cameronchu1** [comment]
Hi Prem,
I also use Chrome browser. When I click "Portfolio" under "Account & Trade", it goes to this page:" https://digital.fidelity.com/ftgw/digital/portfolio/summary "
There is no beta view toggle on this page (screenshot attached).
Thanks,Kan

    On Tuesday, May 23, 2023 at 12:54:41 PM PDT, Prem Patel ***@***.***> wrote:  
 
 


You can find the toggle for the view on the portfolio page on web view. I'm using Chrome and Edge browser. > Thanks,Kan On Tuesday, May 23, 2023 at 05:44:54

**Comment by cameronchu1** [comment]
Hi Prem,
I don't think I can go back to classic view once I chose the new view last year. Now the question is how to make it work in the new view.
I notice that you have a open command with the following target (ORDER_TYPE=E)
" https://oltx.fidelity.com/ftgw/fbc/oftrade/stockInit?ignoreRedirect=Y&ORDER_TYPE=E&ACCOUNT=${account}&SYMBOL=${TICKER}&PRICE_TYPE=L&ORDER_ACTION=S&QTY=${QUANT}&AMOUNT=111.03&SKIP_ORDER_PREVIEW=N "

If I change the ORDER_TYPE=M, it seems to be able to select "LIMIT ORDER" with a amount of 111.03.I am not sure what letter code is for market order, do you know? Also I am not sure where 111.03 come from.
After that, the form get updated but the script can't click on the "Preview Order" button, can you take a quick look and see why?
Thanks,Kan
    On Wednesday, May 24, 2023 at 12:36:32 AM PDT, Kan Chu ***@***.***> wrote:  
 
  Hi Prem,
I also use Chrome browser. When I click "Portfolio" under "Account & Trade", it goes to this page:" https://digital.fidelity.com/ftgw/digital/portfolio/summary "
There is no beta view toggle on this page (screenshot attached).
Thanks,Kan

    On Tuesday, May 23, 2023 at 12:54:41 PM PDT, Prem Patel ***@***.***> wrote:  
 
 


You can find the toggle for the view on the portfolio page on web view. I'm using Chrome and Edge browser. > Thanks,Kan On Tuesday, May 23, 2023 at 05:44:54

**Comment by Prem-ium** [comment]
This is the order UI you should try finding:
![image](https://github.com/Prem-ium/Auto-StockTrader/assets/80719066/8ee44b3e-0aba-4595-883a-4f85d2174642)

**Comment by cameronchu1** [comment]
Hi Prem,
Thanks for your support. 
I find your recommended UI at " https://digital.fidelity.com/ftgw/digital/trade-equity "and use this in the .side script. It works now when I run the SELL test.
I will continue to run tests. I will let you know if I find any other issues.
Thanks,Kan



    On Sunday, May 28, 2023 at 07:31:52 AM PDT, Prem Patel ***@***.***> wrote:  
 
 


This is the order UI you should try finding:
