### ISSUE TITLE
Can quantity be a variable?

### ISSUE THREAD

**Issue by sunk818** [Prem-ium/Auto-StockTrader#19]
In cases where we need to buy more than 1, it'd be nice to have a variable where we can change the qty at the start of the script. 

Also, do you know how to change qty for Schwab buys? The - + clicker isn't changing the qty for me using the Selenium IDE command.

**Comment by Prem-ium** [comment]
Funny enough, I was working on this feature before seeing your issue. I've already committed a quality variable in the Schwab project.
