### ISSUE TITLE
Hey Would you mind helping me set this up?

### ISSUE THREAD

**Issue by BG42424** [Prem-ium/Auto-StockTrader#22]
Hey! I don't mean to bother you but do you think you could help me install your autotrader program? I am not a coder but I installed it and have been able to use selenium to trade stocks with a single brokerage at a time. however, in the notes you also say your program is able to automate trading with multiple brokerages at once meaning I can run one script and buy stocks in multiple accounts at once. Is that correct? If that is so how do I do that? As it does seem to be specifically described in your instructions. and while I am no expert in selenium I am only able to open one. side file and code at a time to run/test. I hope you will be able to help me!

Thank you for your time!

**Comment by Prem-ium** [comment]
You are unable to automate multiple brokerages at once. You can only automate multiple accounts for a single brokerage at any given time on an instance of the Selenium IDE extension.
