### ISSUE TITLE
Fidelity Issue

### ISSUE THREAD

**Issue by codeplea** [Prem-ium/Auto-StockTrader#30]
First, thanks so much for creating this. I am using it with Schwab, Firsttrade, and Vanguard with only occasional minor issues.

I cannot seem to get it to work with Fidelity though. I've tried on both Firefox and Brave browser. It seems to get stuck in the same spot. Is this a known issue?

Here's where it's getting stuck.

![Screenshot 2024-01-25 142859](https://github.com/Prem-ium/Auto-StockTrader/assets/14815717/350d584b-d7c2-4cb6-b523-7c02d6f8d18a)

I can attempt to debug or add more details if needed.

**Comment by Prem-ium** [comment]
Hey @codeplea 👋,

I would be glad to assist you in resolving the issues you are facing.

For Fidelity integration, please consider the following:

1. **Ticket Trading Page View:**
   Ensure that you are utilizing the simplified ticket trading page on Fidelity. Kindly click "View Simplified Ticket" if you have not done so already and attempt to re-run the automation.

2. **FIDELITY_AI Variable:**
   Verify whether your accounts are being correctly selected during the automation process. If not, it is recommended to review and adjust your `FIDELITY_AI` variable settings. Additionally, you have the option to utilize the [Fidelity account helper script](https://github.com/Prem-ium/Auto-StockTrader/blob/9a1b00f568b97b662ba8e69447d7ace2d7e8b8ca/src/Helper_JS_Scripts/Fidelity_Account_Array.js) for expedited retrieval of your account values. Please refer to `.env.example` for the correct formatting of the variable.

Thank you for your valuable support towards this project. In the event that the issues persist, providing a screenshot of your browser page after encountering the error would help in figuring out what could be causing these issues.

**Comment by codeplea** [comment]
I clicked "View Simplified Ticket" and it's working great now. Thanks!
