### ISSUE TITLE
Chase_Auto Buy/Sell issue

### ISSUE THREAD

**Issue by CUBrobocop** [Prem-ium/Auto-StockTrader#31]
Hello. For starters, this is awesome. I really appreciate the work you have done here. You have already saved me a bunch of time with the limited use I have gotten out of it. 

The only issue I have had that I couldn't figure out was with Chase_Auto.side. 
For some reason the line: 
let accounts = ${accounts}; return accounts[${index}].slice(accounts[${index}].indexOf(${target}) + 1);

is returning:
Failed: Cannot read properties of undefined (reading 'slice')

I have tried changing the format of my account numbers in the .env with no luck. Think you could help me figure this out?

Are there any future revisions to update the chase side to work with the new version of the trading experience? 

Thanks!

EDITED: I was able to figure out my mistake. I was accidentally reading the array for CHASE_AI improperly. Sorry about that.

**Comment by Prem-ium** [comment]
Hello CUBrobocop,

I'm glad you were able to figure out the issue. 

From what I can tell, switching to the new trading experience on Chase would slow down the automation and leave it vulnerable to errors more often compared to using the classical version. However, I might add an option to support it for those who prefer the new trading experience sometime in the future.

With the problem resolved, I will close the issue with this comment. Feel free to contact me or open another if you run into any other issues.

Thanks for your support!
