### ISSUE TITLE
Fidelity auto incorrect limit price

### ISSUE THREAD

**Issue by mattthewmoore** [Prem-ium/Auto-StockTrader#32]
Hello, very big fan of the project, impressive really. Recently been running into a problem with fidelity where the limit price entered is 111.03 regardless of what limit price is stored in the .side file. Not sure if you've noticed anything similar.

Any help is appreciated Thanks!

**Comment by Prem-ium** [comment]
The issue has been fixed. Thanks for supporting the project.
