### ISSUE TITLE
Fidelity LIMIT of 100 becomes 1001 when placing order for MINT etf

### ISSUE THREAD

**Issue by mwahal** [Prem-ium/Auto-StockTrader#34]
Hi

I modified the .side file and changed the limit to 100 from 0.46 in the LIMIT section.
When executing step by step in the Selenium IDE, I do see that the value is 100.

1 | store | MINT | TICKER |  
2 | execute script | return 100 | LIMIT |  
3 | store | 1 | QUANT |  
4 | store | 0 | index |  
5 | execute script | return "SLICE_TARGET".trim(); | target |  
6 | store |   |  dyamic
.....

open | https://oltx.fidelity.com/ftgw/fbc/oftrade/stockInit?ignoreRedirect=Y&ORDER_TYPE=E&ACCOUNT=${account}&SYMBOL=${TICK}&PRICE_TYPE=L&ORDER_ACTION=B&QTY=${QUANT}&SKIP_ORDER_PREVIEW=Y |   |  
-- | -- | -- | --
22 | click | css=#action-buy s-assigned-wrapper |   |  
23 | click | css=#market-no s-slot |   |  
24 | wait for element present | id=eqt-ordsel-limit-price-label | 30000 |  
25 | click | id=eqt-ordsel-limit-price-label |   |  
26 | wait for element editable | id=eqt-ordsel-limit-price-field | 30000 |  
27 | type | id=eqt-ordsel-limit-price-field | ${LIMIT} |  
28

Till this point, the LIMIT is 100 in the box.`

28 | click at | id=eqt-ordsel-limit-price-field |   |  
29 | send keys | id=eqt-ordsel-limit-price-field | ${LIMIT}

Now the price has changed to 1001

<code>
MINT
Symbol informationSYMBOLMINT is selected
[Pimco Enhanced Short Maturity Active Exch](https://digital.fidelity.com/prgw/digital/research/quote?symbol=MINT)
price per share$100.33
ARCX
+$0.03 (0.03%)

Refresh Quote
Bid  ARCX
100.33 x 53
Ask  ARCX
100.35 x 19
Volume 
935,374
[Less quote info](javascript:void(0))
Day Range
Low:100.3197High:100.35
52-Week Range
Low:99.32High:100.67
Previous Close
$100.33
Open
$100.33
90-Day Avg. Vol
1,026,981
D
Ex-Dividend
Jun 3, 2024
E
Earnings
--

Buy

Sell

Shares

Dollars
1
SHARE AMOUNT

Market

Limit
Sets the maximum price you're willing to buy.

1001
LIMIT PRICE

Day

GTC

View expanded ticket
Estimated order value, including $0 commission:
$1,001.00

Preview order
</code>

**Comment by Prem-ium** [comment]
This issue should be fixed in the latest commit. Limits will now be set using a URL query parameter alone.
